FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env

WORKDIR /app

# Copy csproj and restore as distinct layers
COPY src/*.csproj ./

RUN dotnet restore

# Copy everything else and build
COPY ./src ./

RUN dotnet publish -c Debug -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.1

RUN apt update && \
    apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

WORKDIR /app

COPY --from=build-env /app/out .

ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "restaurant-dashboard-backend.dll"]