FROM microsoft/dotnet:1.1-sdk

WORKDIR /var/www/aspnetcoreapp

# copy csproj and restore as distinct layers
COPY ./src/restaurant-dashboard-backend.csproj /var/www/aspnetcoreapp

RUN dotnet restore

COPY ./src .

RUN dotnet publish -c Release -o dist

RUN rm -rf bin obj

ENTRYPOINT ["dotnet", "dist/restaurant-dashboard-backend.dll"]