FROM microsoft/dotnet:1.1-sdk

WORKDIR /var/www/aspnetcoreapp

# copy csproj and restore as distinct layers
COPY ./src/restaurant-dashboard-backend.csproj /var/www/aspnetcoreapp

RUN dotnet restore

COPY ./src .

RUN dotnet publish -c Release -o dist

RUN rm -r bin obj Controllers Models Properties Repositories Services Util

RUN rm appsettings.Development.json appsettings.json global.json Program.cs Startup.cs web.config restaurant-dashboard-backend.csproj hosting.json

ENTRYPOINT ["dotnet", "dist/restaurant-dashboard-backend.dll"]