apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: dashboard-backend-app
      docker:
        dockerfile: Dockerfile-dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
