kind: Service
apiVersion: v1
metadata:
  name: dashboard-be-app
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: dashboard-be
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: dashboard-be-app
spec:
  selector:
    matchLabels:
      app: dashboard-be
  replicas: 1
  template:
    metadata:
      labels:
        app: dashboard-be
    spec:
      containers:
      - name: res-dashboard-be
        image: dashboard-backend-app
        ports:
        - containerPort: 5000
