USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_VENTA_DEL_MES]    Script Date: 04/24/2017 20:11:26 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_DASHBOARD_VENTA_DEL_MES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_DASHBOARD_VENTA_DEL_MES]
GO

USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_VENTA_DEL_MES]    Script Date: 04/24/2017 20:11:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE Procedure [dbo].[USP_DASHBOARD_VENTA_DEL_MES]
AS
BEGIN
SET NOCOUNT ON

DECLARE @year INT
DECLARE @month INT
SET @year = (SELECT YEAR(GETDATE()))
SET @month = (SELECT MONTH(GETDATE()))

SELECT SUM(NVENTA) total FROM dbo.MDOCUMENTO
WHERE tTipoDocumento='01' AND YEAR(fRegistro) = @year AND MONTH(fRegistro)=@month

END
SET ANSI_NULLS OFF
GO

