USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_ANULACIONES_DEL_MES]    Script Date: 04/29/2017 11:32:44 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_DASHBOARD_ANULACIONES_DEL_MES]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_DASHBOARD_ANULACIONES_DEL_MES]
GO

USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_ANULACIONES_DEL_MES]    Script Date: 04/29/2017 11:32:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--[USP_DASHBOARD_ANULACIONES_DEL_MES] 2017,3
CREATE Procedure [dbo].[USP_DASHBOARD_ANULACIONES_DEL_MES]
@YEAR INT,
@MONTH TINYINT
AS
BEGIN
SET NOCOUNT ON

SELECT
	COUNT(CASE WHEN a.tMotivoEliminacion='000' THEN 1 ELSE NULL END) AS '000',
	COUNT(CASE WHEN a.tMotivoEliminacion='001' THEN 1 ELSE NULL END) AS '001',
	COUNT(CASE WHEN a.tMotivoEliminacion='002' THEN 1 ELSE NULL END) AS '002',
	COUNT(CASE WHEN a.tMotivoEliminacion='003' THEN 1 ELSE NULL END) AS '003',
	COUNT(CASE WHEN a.tMotivoEliminacion='004' THEN 1 ELSE NULL END) AS '004'
	
FROM APEDIDO a
WHERE tMotivoEliminacion <> '' 
	AND YEAR(fRegistroAnulado) =@YEAR
	AND MONTH(fRegistroAnulado) = @MONTH

END
GO

