USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_VENTA_DEL_DIA]    Script Date: 04/24/2017 20:15:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[USP_DASHBOARD_VENTA_DEL_DIA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[USP_DASHBOARD_VENTA_DEL_DIA]
GO

USE [VENTAS]
GO

/****** Object:  StoredProcedure [dbo].[USP_DASHBOARD_VENTA_DEL_DIA]    Script Date: 04/24/2017 20:15:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE Procedure [dbo].[USP_DASHBOARD_VENTA_DEL_DIA]
AS
BEGIN
SET NOCOUNT ON

DECLARE @date DATETIME
SET @date = CONVERT(DATE, GETDATE())
DECLARE @dateEnd datetime = DATEADD(DAY, 1, @date);

--NVENTA:FLOAT
SELECT ISNULL(SUM(NVENTA),0) [Value]
FROM dbo.MDOCUMENTO
WHERE 
	tTipoDocumento='01' 
	AND fRegistro >= @date 
	AND fRegistro< @dateEnd
END
SET ANSI_NULLS OFF
GO

